// src/pages/Purchase.jsx
import React, { useState, useEffect } from 'react';
import PurchaseData from '../data/PurchaseData';
import PurchaseModals from '../modals/PurchaseModals';

const Purchase = () => {
  // ==================== STATE MANAGEMENT ====================
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [vendors, setVendors] = useState([]);
  const [products, setProducts] = useState([]);
  const [grnRecords, setGrnRecords] = useState([]);
  const [autoGeneratedPOs, setAutoGeneratedPOs] = useState([]);
  const [poRatings, setPoRatings] = useState({});
  const [rescheduleHistory, setRescheduleHistory] = useState({});

  // Counters
  const [poCounter, setPoCounter] = useState(1004);
  const [grnCounter, setGrnCounter] = useState(2002);

  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage] = useState(10);
  const [filteredData, setFilteredData] = useState([]);
  const [totalPages, setTotalPages] = useState(1);

  // Modal States
  const [showCreatePOModal, setShowCreatePOModal] = useState(false);
  const [showEditPOModal, setShowEditPOModal] = useState(false);
  const [showViewPOModal, setShowViewPOModal] = useState(false);
  const [showGRNModal, setShowGRNModal] = useState(false);
  const [showRescheduleModal, setShowRescheduleModal] = useState(false);
  const [showReturnModal, setShowReturnModal] = useState(false);
  const [showRatingModal, setShowRatingModal] = useState(false);

  // Current Item IDs
  const [editingPOId, setEditingPOId] = useState(null);
  const [currentViewingPOId, setCurrentViewingPOId] = useState(null);
  const [currentReschedulePOId, setCurrentReschedulePOId] = useState(null);
  const [currentReturnPOId, setCurrentReturnPOId] = useState(null);
  const [currentRatingPOId, setCurrentRatingPOId] = useState(null);

  // Filters
  const [filters, setFilters] = useState({
    search: '',
    vendor: '',
    status: '',
    dateFrom: '',
    dateTo: ''
  });

  // Forms
  const [poForm, setPOForm] = useState({
    vendorId: '',
    purchaseDate: new Date().toISOString().split('T')[0],
    expectedDeliveryDate: '',
    remarks: ''
  });

  const [productRows, setProductRows] = useState([
    { id: 'row-1', productId: '', quantity: 0, unitPrice: 0 }
  ]);

  const [productSearchTerms, setProductSearchTerms] = useState({});
  const [showProductSuggestions, setShowProductSuggestions] = useState({});

  const [grnForm, setGrnForm] = useState({
    grnNumber: '',
    poNumber: '',
    receivedDate: new Date().toISOString().split('T')[0],
    products: [],
    vehicleNumber: '',
    transportName: '',
    lrNumber: '',
    remarks: ''
  });

  const [rescheduleForm, setRescheduleForm] = useState({
    newExpectedDate: '',
    time: '',
    remarks: ''
  });

  const [returnForm, setReturnForm] = useState({
    returnType: '',
    reason: '',
    products: [],
    remarks: ''
  });

  const [tempRating, setTempRating] = useState({
    quality: 0,
    delivery: 0,
    price: 0,
    comments: ''
  });

  // Toast State
  const [toast, setToast] = useState({ show: false, message: '', type: 'info' });

  // ==================== LOAD DATA ====================
  useEffect(() => {
    setVendors(PurchaseData.getVendors());
    setProducts(PurchaseData.getProducts());
    setPurchaseOrders(PurchaseData.getPurchaseOrders());
    setGrnRecords(PurchaseData.getGRNRecords());
    setAutoGeneratedPOs(PurchaseData.getAutoGeneratedPOs());
    setPoRatings(PurchaseData.getPoRatings());
    setRescheduleHistory(PurchaseData.getRescheduleHistory());
  }, []);

  // ==================== APPLY FILTERS ====================
  useEffect(() => {
    let filtered = [...purchaseOrders];

    if (filters.search) {
      const searchLower = filters.search.toLowerCase();
      filtered = filtered.filter(po => 
        po.poNumber.toLowerCase().includes(searchLower) ||
        po.vendorName.toLowerCase().includes(searchLower) ||
        po.grnNumber?.toLowerCase().includes(searchLower)
      );
    }

    if (filters.vendor) {
      filtered = filtered.filter(po => po.vendorId === filters.vendor);
    }

    if (filters.status) {
      filtered = filtered.filter(po => po.status === filters.status);
    }

    if (filters.dateFrom) {
      filtered = filtered.filter(po => new Date(po.purchaseDate) >= new Date(filters.dateFrom));
    }

    if (filters.dateTo) {
      filtered = filtered.filter(po => new Date(po.purchaseDate) <= new Date(filters.dateTo));
    }

    const total = Math.ceil(filtered.length / itemsPerPage);
    setTotalPages(total);
    const startIndex = (currentPage - 1) * itemsPerPage;
    setFilteredData(filtered.slice(startIndex, startIndex + itemsPerPage));
  }, [purchaseOrders, filters, currentPage, itemsPerPage]);

  // ==================== UTILITY FUNCTIONS ====================
  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric'
    });
  };

  const formatCurrency = (amount) => {
    return `₹${amount.toLocaleString('en-IN')}`;
  };

  const showToast = (message, type = 'info') => {
    setToast({ show: true, message, type });
    setTimeout(() => {
      setToast({ show: false, message: '', type: 'info' });
    }, 3000);
  };

  const getStatusBadge = (status) => {
    const config = {
      pending: { bg: 'bg-yellow-100', text: 'text-yellow-700', border: 'border-yellow-300', icon: 'fa-clock' },
      completed: { bg: 'bg-green-100', text: 'text-green-700', border: 'border-green-300', icon: 'fa-check-circle' },
      cancelled: { bg: 'bg-red-100', text: 'text-red-700', border: 'border-red-300', icon: 'fa-times-circle' },
      draft: { bg: 'bg-purple-100', text: 'text-purple-700', border: 'border-purple-300', icon: 'fa-file' }
    };
    const cfg = config[status] || config.pending;
    return (
      <span className={`inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-bold border ${cfg.bg} ${cfg.text} ${cfg.border}`}>
        <i className={`fas ${cfg.icon}`}></i>
        {status.toUpperCase()}
      </span>
    );
  };

  const stats = PurchaseData.calculateStatistics();

  // ==================== CREATE PO HANDLERS ====================
  const handleOpenCreatePO = () => {
    setPOForm({
      vendorId: '',
      purchaseDate: new Date().toISOString().split('T')[0],
      expectedDeliveryDate: '',
      remarks: ''
    });
    setProductRows([{ id: 'row-1', productId: '', quantity: 0, unitPrice: 0 }]);
    setProductSearchTerms({});
    setShowProductSuggestions({});
    setShowCreatePOModal(true);
  };

  const handleAddProductRow = () => {
    setProductRows([...productRows, {
      id: `row-${Date.now()}`,
      productId: '',
      quantity: 0,
      unitPrice: 0
    }]);
  };

  const handleRemoveProductRow = (rowId) => {
    if (productRows.length > 1) {
      setProductRows(productRows.filter(row => row.id !== rowId));
    }
  };

  const handleProductSearch = (rowId, term) => {
    setProductSearchTerms({ ...productSearchTerms, [rowId]: term });
    setShowProductSuggestions({ ...showProductSuggestions, [rowId]: !!term.trim() });
  };

  const handleSelectProduct = (rowId, product) => {
    setProductRows(productRows.map(row => 
      row.id === rowId ? { ...row, productId: product.id, unitPrice: product.unitPrice } : row
    ));
    setProductSearchTerms({ ...productSearchTerms, [rowId]: product.productName });
    setShowProductSuggestions({ ...showProductSuggestions, [rowId]: false });
  };

  const getFilteredProducts = (term) => {
    if (!term) return [];
    return PurchaseData.searchProducts(term).slice(0, 5);
  };

  const calculateOrderTotal = () => {
    return productRows.reduce((sum, row) => sum + (row.quantity * row.unitPrice), 0);
  };

  const handleCreatePO = () => {
    if (!poForm.expectedDeliveryDate) {
      showToast('Please fill all required fields', 'error');
      return;
    }

    const validProducts = productRows.filter(row => row.productId && row.quantity > 0);
    if (validProducts.length === 0) {
      showToast('Please add at least one product with quantity', 'error');
      return;
    }

    const vendor = vendors.find(v => v.id === poForm.vendorId);
    const newPO = {
      id: `PO-${poCounter}`,
      poNumber: `PO-${poCounter}`,
      vendorId: poForm.vendorId || 'V001',
      vendorName: vendor?.vendorName || 'Default Vendor',
      purchaseDate: poForm.purchaseDate,
      expectedDeliveryDate: poForm.expectedDeliveryDate,
      products: validProducts.map(row => {
        const product = products.find(p => p.id === row.productId);
        return {
          productId: row.productId,
          productName: product?.productName || '',
          orderedQty: row.quantity,
          unitPrice: row.unitPrice
        };
      }),
      purchasePrice: calculateOrderTotal(),
      status: 'pending',
      remarks: poForm.remarks,
      grnNumber: null,
      createdAt: new Date().toISOString()
    };

    setPurchaseOrders([newPO, ...purchaseOrders]);
    setPoCounter(poCounter + 1);
    showToast('Purchase Order created successfully!', 'success');
    setShowCreatePOModal(false);
  };

  // ==================== EDIT PO ====================
  const handleOpenEditPO = (po) => {
    setEditingPOId(po.id);
    setPOForm({
      vendorId: po.vendorId,
      purchaseDate: po.purchaseDate,
      expectedDeliveryDate: po.expectedDeliveryDate,
      remarks: po.remarks || ''
    });

    const newTerms = {};
    po.products.forEach((p, idx) => {
      newTerms[`row-${idx}`] = p.productName;
    });
    setProductSearchTerms(newTerms);

    setProductRows(po.products.map((p, idx) => ({
      id: `row-${idx}`,
      productId: p.productId,
      quantity: p.orderedQty,
      unitPrice: p.unitPrice
    })));
    setShowEditPOModal(true);
  };

  const handleUpdatePO = () => {
    if (!poForm.expectedDeliveryDate) {
      showToast('Please fill all required fields', 'error');
      return;
    }

    const validProducts = productRows.filter(row => row.productId && row.quantity > 0);
    if (validProducts.length === 0) {
      showToast('Please add at least one product', 'error');
      return;
    }

    const vendor = vendors.find(v => v.id === poForm.vendorId);
    setPurchaseOrders(purchaseOrders.map(po => {
      if (po.id === editingPOId) {
        return {
          ...po,
          vendorId: poForm.vendorId,
          vendorName: vendor?.vendorName || '',
          purchaseDate: poForm.purchaseDate,
          expectedDeliveryDate: poForm.expectedDeliveryDate,
          products: validProducts.map(row => {
            const product = products.find(p => p.id === row.productId);
            return {
              productId: row.productId,
              productName: product?.productName || '',
              orderedQty: row.quantity,
              unitPrice: row.unitPrice
            };
          }),
          purchasePrice: calculateOrderTotal(),
          remarks: poForm.remarks
        };
      }
      return po;
    }));

    showToast('Purchase Order updated successfully!', 'success');
    setShowEditPOModal(false);
    setEditingPOId(null);
  };

  // ==================== DELETE PO ====================
  const handleDeletePO = (po) => {
    if (window.confirm(`Are you sure you want to delete ${po.poNumber}?`)) {
      setPurchaseOrders(purchaseOrders.filter(p => p.id !== po.id));
      showToast('Purchase Order deleted successfully', 'success');
    }
  };

  // ==================== VIEW PO ====================
  const handleViewPO = (po) => {
    setCurrentViewingPOId(po.id);
    setShowViewPOModal(true);
  };

  const getCurrentViewingPO = () => {
    return purchaseOrders.find(po => po.id === currentViewingPOId);
  };

  // ==================== GRN ====================
  const handleOpenGRN = (po) => {
    setCurrentViewingPOId(po.id);
    setGrnForm({
      grnNumber: `GRN-${grnCounter}`,
      poNumber: po.poNumber,
      receivedDate: new Date().toISOString().split('T')[0],
      products: po.products.map(p => ({
        ...p,
        receivedQty: p.orderedQty,
        status: 'received',
        remarks: ''
      })),
      vehicleNumber: '',
      transportName: '',
      lrNumber: '',
      remarks: ''
    });
    setShowGRNModal(true);
  };

  const handleGRNProductChange = (productId, field, value) => {
    setGrnForm({
      ...grnForm,
      products: grnForm.products.map(p => 
        p.productId === productId ? { ...p, [field]: value } : p
      )
    });
  };

  const handleCreateGRN = () => {
    const po = purchaseOrders.find(p => p.poNumber === grnForm.poNumber);
    if (!po) return;

    if (!grnForm.vehicleNumber || !grnForm.lrNumber) {
      showToast('Please fill all required transport details', 'error');
      return;
    }

    const grnNumber = `GRN-${grnCounter}`;
    const newGRN = {
      id: grnNumber,
      grnNumber,
      poNumber: grnForm.poNumber,
      poId: po.id,
      vendorId: po.vendorId,
      vendorName: po.vendorName,
      receivedDate: grnForm.receivedDate,
      products: grnForm.products,
      vehicleNumber: grnForm.vehicleNumber,
      transportName: grnForm.transportName,
      lrNumber: grnForm.lrNumber,
      remarks: grnForm.remarks,
      createdAt: new Date().toISOString()
    };

    setGrnRecords([newGRN, ...grnRecords]);
    setPurchaseOrders(purchaseOrders.map(p => 
      p.id === po.id ? { ...p, grnNumber, status: 'completed' } : p
    ));
    setGrnCounter(grnCounter + 1);
    showToast('GRN created successfully!', 'success');
    setShowGRNModal(false);
  };

  // ==================== RESCHEDULE ====================
  const handleOpenReschedule = (po) => {
    setCurrentReschedulePOId(po.id);
    setRescheduleForm({
      newExpectedDate: po.expectedDeliveryDate,
      time: '',
      remarks: ''
    });
    setShowRescheduleModal(true);
  };

  const handleReschedulePO = () => {
    if (!rescheduleForm.newExpectedDate || !rescheduleForm.remarks) {
      showToast('Please fill all required fields', 'error');
      return;
    }

    const po = purchaseOrders.find(p => p.id === currentReschedulePOId);
    if (!po) return;

    setRescheduleHistory({
      ...rescheduleHistory,
      [po.id]: [...(rescheduleHistory[po.id] || []), {
        oldDate: po.expectedDeliveryDate,
        newDate: rescheduleForm.newExpectedDate,
        reason: rescheduleForm.remarks,
        remarks: rescheduleForm.remarks,
        rescheduledAt: new Date().toISOString()
      }]
    });

    setPurchaseOrders(purchaseOrders.map(p =>
      p.id === currentReschedulePOId
        ? { ...p, expectedDeliveryDate: rescheduleForm.newExpectedDate }
        : p
    ));

    showToast('Delivery date rescheduled successfully!', 'success');
    setShowRescheduleModal(false);
  };

  // ==================== RETURN ====================
  const handleOpenReturn = (po) => {
    setCurrentReturnPOId(po.id);
    setReturnForm({
      returnType: '',
      reason: '',
      products: po.products.map(p => ({
        ...p,
        returnQty: 0,
        selected: false,
        remarks: ''
      })),
      remarks: ''
    });
    setShowReturnModal(true);
  };

  const handleReturnProductChange = (productId, field, value) => {
    setReturnForm({
      ...returnForm,
      products: returnForm.products.map(p =>
        p.productId === productId ? { ...p, [field]: value } : p
      )
    });
  };

  const handleCreateReturn = () => {
    const selected = returnForm.products.filter(p => p.selected && p.returnQty > 0);
    if (selected.length === 0) {
      showToast('Please select at least one product to return', 'error');
      return;
    }
    if (!returnForm.reason || !returnForm.remarks) {
      showToast('Please provide reason and detailed remarks', 'error');
      return;
    }

    showToast('Return request created successfully!', 'success');
    setShowReturnModal(false);
  };

  // ==================== RATING ====================
  const handleOpenRating = (po) => {
    setCurrentRatingPOId(po.id);
    setTempRating(poRatings[po.id] || { quality: 0, delivery: 0, price: 0, comments: '' });
    setShowRatingModal(true);
  };

  const handleSubmitRating = () => {
    if (tempRating.quality === 0 || tempRating.delivery === 0 || tempRating.price === 0) {
      showToast('Please provide all ratings', 'error');
      return;
    }
    setPoRatings({ ...poRatings, [currentRatingPOId]: tempRating });
    showToast('Rating submitted successfully!', 'success');
    setShowRatingModal(false);
  };

  // ==================== DRAFT ACTIONS ====================
  const handleConvertDraft = (draft) => {
    const vendor = vendors.find(v => v.id === draft.vendorId);
    const newPO = {
      id: `PO-${poCounter}`,
      poNumber: `PO-${poCounter}`,
      vendorId: draft.vendorId,
      vendorName: vendor?.vendorName || '',
      purchaseDate: new Date().toISOString().split('T')[0],
      expectedDeliveryDate: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
      products: [{
        productId: draft.productId,
        productName: draft.productName,
        orderedQty: draft.suggestedQuantity,
        unitPrice: draft.unitPrice || 0
      }],
      purchasePrice: draft.suggestedQuantity * (draft.unitPrice || 0),
      status: 'pending',
      remarks: `Converted from ${draft.id}`,
      grnNumber: null,
      createdAt: new Date().toISOString()
    };

    setPurchaseOrders([newPO, ...purchaseOrders]);
    setAutoGeneratedPOs(autoGeneratedPOs.filter(po => po.id !== draft.id));
    setPoCounter(poCounter + 1);
    showToast('Draft converted to Purchase Order!', 'success');
  };

  const handleDeleteDraft = (draftId) => {
    setAutoGeneratedPOs(autoGeneratedPOs.filter(po => po.id !== draftId));
    showToast('Draft order deleted', 'success');
  };

  const clearFilters = () => {
    setFilters({ search: '', vendor: '', status: '', dateFrom: '', dateTo: '' });
    setCurrentPage(1);
  };

  const refreshData = () => {
    setPurchaseOrders(PurchaseData.getPurchaseOrders());
    setGrnRecords(PurchaseData.getGRNRecords());
    setAutoGeneratedPOs(PurchaseData.getAutoGeneratedPOs());
    showToast('Data refreshed successfully', 'success');
  };

  // ==================== JSX RETURN ====================
  return (
    <div className="min-h-screen bg-gradient-to-br from-cyan-50 via-white to-teal-50 p-6">

      {/* Toast Notification */}
      {toast.show && (
        <div className={`fixed top-6 right-6 z-[9999] px-6 py-4 rounded-lg shadow-2xl border-2 flex items-center gap-3 animate-slide-in-right ${
          toast.type === 'success' ? 'bg-green-50 border-green-300 text-green-800' :
          toast.type === 'error' ? 'bg-red-50 border-red-300 text-red-800' :
          toast.type === 'warning' ? 'bg-yellow-50 border-yellow-300 text-yellow-800' :
          'bg-blue-50 border-blue-300 text-blue-800'
        }`}>
          <i className={`fas text-xl ${
            toast.type === 'success' ? 'fa-check-circle text-green-600' :
            toast.type === 'error' ? 'fa-times-circle text-red-600' :
            toast.type === 'warning' ? 'fa-exclamation-triangle text-yellow-600' :
            'fa-info-circle text-blue-600'
          }`}></i>
          <span className="font-semibold">{toast.message}</span>
          <button
            onClick={() => setToast({ ...toast, show: false })}
            className="ml-4 text-gray-500 hover:text-gray-700"
          >
            <i className="fas fa-times"></i>
          </button>
        </div>
      )}

      {/* Page Header */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 mb-6">
        <div className="flex justify-between items-center flex-wrap gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-3 mb-1">
              <i className="fas fa-shopping-cart text-teal-500"></i>
              Purchase Management
            </h1>
            <p className="text-sm text-gray-600">
              Manage purchase orders, GRN, vendor transactions with ratings & return tracking
            </p>
          </div>
          <button
            onClick={handleOpenCreatePO}
            className="px-6 py-2.5 bg-gradient-to-r from-teal-400 to-teal-700 text-white rounded-lg text-sm font-semibold hover:-translate-y-0.5 hover:shadow-lg transition-all duration-200 flex items-center gap-2"
          >
            <i className="fas fa-plus"></i>
            Create Purchase Order
          </button>
        </div>
      </div>

      {/* Statistics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6">
        {/* Total Purchase Orders */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:-translate-y-1 hover:shadow-lg transition-all duration-200">
          <div className="flex justify-between items-start mb-3">
            <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide flex items-center gap-2">
              <i className="fas fa-file-invoice text-teal-500"></i>
              Total Purchase Orders
            </div>
          </div>
          <div className="text-3xl font-extrabold text-gray-800 mb-2">{stats.totalPOs}</div>
          <div className="text-xs font-semibold text-green-600 flex items-center gap-1">
            <i className="fas fa-arrow-up"></i>
            {stats.thisMonthPOs} this month
          </div>
        </div>

        {/* Pending Approvals */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:-translate-y-1 hover:shadow-lg transition-all duration-200">
          <div className="flex justify-between items-start mb-3">
            <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide flex items-center gap-2">
              <i className="fas fa-clock text-yellow-500"></i>
              Pending Approvals
            </div>
          </div>
          <div className="text-3xl font-extrabold text-gray-800 mb-2">{stats.pendingApprovals}</div>
          <div className="text-xs font-semibold text-yellow-600 flex items-center gap-1">
            <i className="fas fa-exclamation-triangle"></i>
            Needs Attention
          </div>
        </div>

        {/* GRNs Generated */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:-translate-y-1 hover:shadow-lg transition-all duration-200">
          <div className="flex justify-between items-start mb-3">
            <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide flex items-center gap-2">
              <i className="fas fa-clipboard-check text-green-500"></i>
              GRNs Generated
            </div>
          </div>
          <div className="text-3xl font-extrabold text-gray-800 mb-2">{stats.totalGRNs}</div>
          <div className="text-xs font-semibold text-green-600 flex items-center gap-1">
            <i className="fas fa-check"></i>
            {stats.thisMonthGRNs} this month
          </div>
        </div>

        {/* Draft Orders */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:-translate-y-1 hover:shadow-lg transition-all duration-200">
          <div className="flex justify-between items-start mb-3">
            <div className="text-xs font-semibold text-gray-600 uppercase tracking-wide flex items-center gap-2">
              <i className="fas fa-file-alt text-purple-500"></i>
              Draft Orders
            </div>
          </div>
          <div className="text-3xl font-extrabold text-gray-800 mb-2">{stats.draftOrders}</div>
          <div className="text-xs font-semibold text-blue-600 flex items-center gap-1">
            <i className="fas fa-info-circle"></i>
            Auto-Generated
          </div>
        </div>
      </div>

      {/* Filters Section */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 mb-6">
        <div className="p-4 border-b-2 border-gray-200 bg-gradient-to-r from-teal-50 to-cyan-50">
          <h3 className="text-sm font-bold text-gray-700 flex items-center gap-2">
            <i className="fas fa-filter text-teal-600"></i>
            Filters
          </h3>
        </div>
        <div className="p-5">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">Search PO/GRN</label>
              <input
                type="text"
                value={filters.search}
                onChange={(e) => setFilters({ ...filters, search: e.target.value })}
                placeholder="Search by PO number, vendor..."
                className="w-full py-2 px-3 border-2 border-gray-200 rounded-md text-sm focus:outline-none focus:border-teal-400 focus:ring-4 focus:ring-cyan-100 transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">Vendor</label>
              <select
                value={filters.vendor}
                onChange={(e) => setFilters({ ...filters, vendor: e.target.value })}
                className="w-full py-2 px-3 border-2 border-gray-200 rounded-md text-sm focus:outline-none focus:border-teal-400 focus:ring-4 focus:ring-cyan-100 transition-all cursor-pointer"
              >
                <option value="">All Vendors</option>
                {vendors.map(v => (
                  <option key={v.id} value={v.id}>{v.vendorName}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">Status</label>
              <select
                value={filters.status}
                onChange={(e) => setFilters({ ...filters, status: e.target.value })}
                className="w-full py-2 px-3 border-2 border-gray-200 rounded-md text-sm focus:outline-none focus:border-teal-400 focus:ring-4 focus:ring-cyan-100 transition-all cursor-pointer"
              >
                <option value="">All Status</option>
                <option value="draft">Draft</option>
                <option value="pending">Pending</option>
                <option value="completed">Completed</option>
                <option value="cancelled">Cancelled</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">Date From</label>
              <input
                type="date"
                value={filters.dateFrom}
                onChange={(e) => setFilters({ ...filters, dateFrom: e.target.value })}
                className="w-full py-2 px-3 border-2 border-gray-200 rounded-md text-sm focus:outline-none focus:border-teal-400 focus:ring-4 focus:ring-cyan-100 transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">Date To</label>
              <input
                type="date"
                value={filters.dateTo}
                onChange={(e) => setFilters({ ...filters, dateTo: e.target.value })}
                className="w-full py-2 px-3 border-2 border-gray-200 rounded-md text-sm focus:outline-none focus:border-teal-400 focus:ring-4 focus:ring-cyan-100 transition-all"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">&nbsp;</label>
              <button
                onClick={() => setCurrentPage(1)}
                className="w-full px-4 py-2 bg-gradient-to-r from-teal-400 to-teal-700 text-white rounded-md text-sm font-semibold hover:-translate-y-0.5 hover:shadow-md transition-all duration-200 flex items-center justify-center gap-2"
              >
                <i className="fas fa-filter"></i>
                Apply
              </button>
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1.5">&nbsp;</label>
              <button
                onClick={clearFilters}
                className="w-full px-4 py-2 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-md text-sm font-semibold hover:-translate-y-0.5 hover:shadow-md transition-all duration-200 flex items-center justify-center gap-2"
              >
                <i className="fas fa-times"></i>
                Clear
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Purchase Orders Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mb-6">
        <div className="p-4 border-b-2 border-gray-200 bg-gradient-to-r from-teal-50 to-cyan-50 flex justify-between items-center">
          <h2 className="text-lg font-bold text-gray-800 flex items-center gap-2">
            <i className="fas fa-shopping-cart text-teal-600"></i>
            Purchase Orders & GRN ({purchaseOrders.length})
          </h2>
          <button
            onClick={refreshData}
            className="px-4 py-1.5 bg-teal-100 text-teal-700 rounded-md text-sm font-semibold hover:bg-teal-200 transition-colors flex items-center gap-2"
          >
            <i className="fas fa-sync-alt"></i>
            Refresh
          </button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1200px]">
            <thead className="bg-gray-100 border-b-2 border-gray-200">
              <tr>
                {['PO Number', 'GRN Number', 'Purchase Date', 'Vendor', 'Products', 'Quantity', 'Amount', 'Status', 'Reschedule', 'Actions'].map((h, i) => (
                  <th key={i} className="px-4 py-3 text-left text-xs font-bold text-gray-600 uppercase tracking-wider whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filteredData.length === 0 ? (
                <tr>
                  <td colSpan="10" className="px-4 py-16 text-center">
                    <div className="flex flex-col items-center justify-center">
                      <i className="fas fa-inbox text-gray-300 text-6xl mb-4"></i>
                      <p className="text-gray-500 text-lg font-semibold mb-2">No Purchase Orders Found</p>
                      <p className="text-gray-400 text-sm">Try adjusting your filters or create a new purchase order</p>
                    </div>
                  </td>
                </tr>
              ) : (
                filteredData.map(po => {
                  const totalQty = po.products.reduce((s, p) => s + p.orderedQty, 0);
                  const rescheduleCount = rescheduleHistory[po.id]?.length || 0;
                  const rating = poRatings[po.id];
                  const avgRating = rating ? ((rating.quality + rating.delivery + rating.price) / 3).toFixed(1) : null;

                  return (
                    <tr key={po.id} className="hover:bg-cyan-50 transition-colors">
                      <td className="px-4 py-3">
                        <div className="text-sm font-bold text-teal-700">{po.poNumber}</div>
                        <div className="text-xs text-gray-500">{formatDate(po.purchaseDate)}</div>
                      </td>
                      <td className="px-4 py-3">
                        {po.grnNumber ? (
                          <span className="text-sm font-semibold text-green-700">{po.grnNumber}</span>
                        ) : (
                          <span className="text-sm text-gray-400 italic">Pending</span>
                        )}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-600">{formatDate(po.purchaseDate)}</td>
                      <td className="px-4 py-3">
                        <div className="text-sm font-semibold text-gray-800">{po.vendorName}</div>
                        {avgRating && (
                          <div className="text-xs text-amber-600 flex items-center gap-1 mt-1">
                            <i className="fas fa-star"></i>
                            {avgRating}/5.0
                          </div>
                        )}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-600">{po.products.length} item(s)</td>
                      <td className="px-4 py-3 text-sm font-semibold text-gray-700">{totalQty}</td>
                      <td className="px-4 py-3 text-sm font-bold text-gray-800">{formatCurrency(po.purchasePrice)}</td>
                      <td className="px-4 py-3">{getStatusBadge(po.status)}</td>
                      <td className="px-4 py-3">
                        {rescheduleCount > 0 ? (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-purple-100 text-purple-700 rounded-full text-xs font-semibold">
                            <i className="fas fa-history"></i>
                            {rescheduleCount}x
                          </span>
                        ) : (
                          <span className="text-xs text-gray-400">-</span>
                        )}
                      </td>
                      <td className="px-4 py-3">
                        <div className="flex flex-wrap gap-1">
                          <button
                            onClick={() => handleViewPO(po)}
                            className="px-2.5 py-1.5 bg-blue-100 text-blue-700 rounded text-xs font-semibold hover:bg-blue-200 transition-all"
                            title="View Details"
                          >
                            <i className="fas fa-eye"></i>
                          </button>
                          <button
                            onClick={() => handleOpenEditPO(po)}
                            className="px-2.5 py-1.5 bg-yellow-100 text-yellow-700 rounded text-xs font-semibold hover:bg-yellow-200 transition-all"
                            title="Edit PO"
                          >
                            <i className="fas fa-edit"></i>
                          </button>
                          {!po.grnNumber && (
                            <button
                              onClick={() => handleOpenGRN(po)}
                              className="px-2.5 py-1.5 bg-green-100 text-green-700 rounded text-xs font-semibold hover:bg-green-200 transition-all"
                              title="Generate GRN"
                            >
                              <i className="fas fa-clipboard-check"></i>
                            </button>
                          )}
                          <button
                            onClick={() => handleOpenReschedule(po)}
                            className="px-2.5 py-1.5 bg-purple-100 text-purple-700 rounded text-xs font-semibold hover:bg-purple-200 transition-all"
                            title="Reschedule"
                          >
                            <i className="fas fa-calendar-alt"></i>
                          </button>
                          <button
                            onClick={() => handleOpenReturn(po)}
                            className="px-2.5 py-1.5 bg-orange-100 text-orange-700 rounded text-xs font-semibold hover:bg-orange-200 transition-all"
                            title="Return/Replace"
                          >
                            <i className="fas fa-undo"></i>
                          </button>
                          <button
                            onClick={() => handleOpenRating(po)}
                            className="px-2.5 py-1.5 bg-amber-100 text-amber-700 rounded text-xs font-semibold hover:bg-amber-200 transition-all"
                            title="Rate Order"
                          >
                            <i className="fas fa-star"></i>
                          </button>
                          <button
                            onClick={() => handleDeletePO(po)}
                            className="px-2.5 py-1.5 bg-red-100 text-red-700 rounded text-xs font-semibold hover:bg-red-200 transition-all"
                            title="Delete"
                          >
                            <i className="fas fa-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="p-4 border-t-2 border-gray-200 bg-gray-50 flex justify-center gap-2 flex-wrap">
            <button 
              onClick={() => setCurrentPage(Math.max(1, currentPage - 1))} 
              disabled={currentPage === 1}
              className="px-4 py-2 border-2 border-gray-300 rounded-md text-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:border-teal-400 hover:bg-cyan-50 transition-all"
            >
              <i className="fas fa-chevron-left mr-1"></i> Previous
            </button>

            {[...Array(totalPages)].map((_, i) => (
              <button
                key={i}
                className={`px-4 py-2 border-2 rounded-md text-sm font-semibold transition-all ${
                  currentPage === i + 1
                    ? 'bg-gradient-to-r from-teal-400 to-teal-700 text-white border-teal-500'
                    : 'border-gray-300 hover:border-teal-400 hover:bg-cyan-50'
                }`}
                onClick={() => setCurrentPage(i + 1)}
              >
                {i + 1}
              </button>
            ))}

            <button 
              onClick={() => setCurrentPage(Math.min(totalPages, currentPage + 1))} 
              disabled={currentPage === totalPages}
              className="px-4 py-2 border-2 border-gray-300 rounded-md text-sm font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:border-teal-400 hover:bg-cyan-50 transition-all"
            >
              Next <i className="fas fa-chevron-right ml-1"></i>
            </button>
          </div>
        )}
      </div>

      {/* Draft Orders Table */}
      {autoGeneratedPOs.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mb-6">
          <div className="p-4 border-b-2 border-gray-200 bg-gradient-to-r from-purple-50 to-pink-50">
            <h2 className="text-lg font-bold text-gray-800 flex items-center gap-2">
              <i className="fas fa-robot text-purple-600"></i>
              Auto-Generated Purchase Orders (Draft) ({autoGeneratedPOs.length})
            </h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-100 border-b-2 border-gray-200">
                <tr>
                  {['Draft ID', 'Product', 'Vendor', 'Suggested Qty', 'Unit Price', 'Reason', 'Actions'].map((h, i) => (
                    <th key={i} className="px-4 py-3 text-left text-xs font-bold text-gray-600 uppercase tracking-wider whitespace-nowrap">
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {autoGeneratedPOs.map(draft => (
                  <tr key={draft.id} className="hover:bg-purple-50 transition-colors">
                    <td className="px-4 py-3">
                      <span className="text-sm font-bold text-purple-700">{draft.id}</span>
                    </td>
                    <td className="px-4 py-3 text-sm font-semibold text-gray-800">{draft.productName}</td>
                    <td className="px-4 py-3 text-sm text-gray-600">{vendors.find(v => v.id === draft.vendorId)?.vendorName || 'Unknown'}</td>
                    <td className="px-4 py-3 text-sm font-semibold text-gray-700">{draft.suggestedQuantity}</td>
                    <td className="px-4 py-3 text-sm font-bold text-gray-800">{formatCurrency(draft.unitPrice || 0)}</td>
                    <td className="px-4 py-3 text-sm text-gray-600">{draft.reason}</td>
                    <td className="px-4 py-3">
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleConvertDraft(draft)}
                          className="px-3 py-1.5 bg-purple-100 text-purple-700 rounded text-xs font-semibold hover:bg-purple-200 transition-all"
                        >
                          <i className="fas fa-check mr-1"></i>
                          Convert to PO
                        </button>
                        <button
                          onClick={() => handleDeleteDraft(draft.id)}
                          className="px-3 py-1.5 bg-red-100 text-red-700 rounded text-xs font-semibold hover:bg-red-200 transition-all"
                        >
                          <i className="fas fa-trash"></i>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* MODALS */}
      <PurchaseModals
        // Modal States
        showCreatePOModal={showCreatePOModal}
        setShowCreatePOModal={setShowCreatePOModal}
        showEditPOModal={showEditPOModal}
        setShowEditPOModal={setShowEditPOModal}
        showViewPOModal={showViewPOModal}
        setShowViewPOModal={setShowViewPOModal}
        showGRNModal={showGRNModal}
        setShowGRNModal={setShowGRNModal}
        showRescheduleModal={showRescheduleModal}
        setShowRescheduleModal={setShowRescheduleModal}
        showReturnModal={showReturnModal}
        setShowReturnModal={setShowReturnModal}
        showRatingModal={showRatingModal}
        setShowRatingModal={setShowRatingModal}

        // Forms
        poForm={poForm}
        setPOForm={setPOForm}
        productRows={productRows}
        setProductRows={setProductRows}
        grnForm={grnForm}
        setGrnForm={setGrnForm}
        rescheduleForm={rescheduleForm}
        setRescheduleForm={setRescheduleForm}
        returnForm={returnForm}
        setReturnForm={setReturnForm}
        tempRating={tempRating}
        setTempRating={setTempRating}

        // Product Search
        productSearchTerms={productSearchTerms}
        setProductSearchTerms={setProductSearchTerms}
        showProductSuggestions={showProductSuggestions}
        setShowProductSuggestions={setShowProductSuggestions}

        // Data
        vendors={vendors}
        products={products}
        purchaseOrders={purchaseOrders}

        // Handlers
        handleCreatePO={handleCreatePO}
        handleUpdatePO={handleUpdatePO}
        handleAddProductRow={handleAddProductRow}
        handleRemoveProductRow={handleRemoveProductRow}
        handleProductSearch={handleProductSearch}
        handleSelectProduct={handleSelectProduct}
        getFilteredProducts={getFilteredProducts}
        calculateOrderTotal={calculateOrderTotal}
        handleGRNProductChange={handleGRNProductChange}
        handleCreateGRN={handleCreateGRN}
        handleReschedulePO={handleReschedulePO}
        handleReturnProductChange={handleReturnProductChange}
        handleCreateReturn={handleCreateReturn}
        handleSubmitRating={handleSubmitRating}
        getCurrentViewingPO={getCurrentViewingPO}
        formatDate={formatDate}
        formatCurrency={formatCurrency}
        getStatusBadge={getStatusBadge}
        editingPOId={editingPOId}
      />

    </div>
  );
};

export default Purchase;